-- V1__initial_schema.sql (PostgreSQL Version)

-- =========================
-- Security / Auth tables
-- =========================
CREATE TABLE roles (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles(name);

CREATE TABLE capabilities (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,
    CONSTRAINT pk_capabilities PRIMARY KEY (id),
    CONSTRAINT uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities(name);

CREATE TABLE roles_capabilities (
    role_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role FOREIGN KEY (role_id) 
        REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability FOREIGN KEY (capability_id) 
        REFERENCES capabilities(id) ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities(capability_id);

CREATE TABLE users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    uid UUID NOT NULL, 
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NULL, 
    lastname VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_uid UNIQUE (uid),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE INDEX idx_users_uid ON users(uid);
CREATE INDEX ix_users_deleted ON users(deleted);
CREATE INDEX ix_users_deleted_at ON users(deleted_at);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL, 
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) 
        REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) 
        REFERENCES roles(id) ON DELETE CASCADE
);

CREATE INDEX idx_users_roles_role_id ON users_roles(role_id);

-- =========================
-- Domain entities
-- =========================
CREATE TABLE properties (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    host_id BIGINT NOT NULL, 
    title VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    address VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL, 
    hourly_rate NUMERIC(10, 2) NOT NULL,
    half_day_rate NUMERIC(10, 2) NOT NULL,
    type VARCHAR(255) NULL,
    min_hours INT NOT NULL,
    max_hours INT NOT NULL,
    size_sqm INT NOT NULL,
    capacity INT NOT NULL,
    zip VARCHAR(255) NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    longitude NUMERIC(10, 8) NOT NULL,
    latitude NUMERIC(9, 8) NOT NULL,
    description TEXT NULL, 
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_properties PRIMARY KEY (id),
    CONSTRAINT fk_properties_host FOREIGN KEY (host_id)
        REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_properties_deleted ON properties(deleted);
CREATE INDEX idx_properties_deleted_at ON properties(deleted_at);

CREATE TABLE bookings (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_id BIGINT NOT NULL,
    guest_id BIGINT NOT NULL, -- references User's id
    start_datetime TIMESTAMPTZ NOT NULL,
    end_datetime TIMESTAMPTZ NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    host_fee NUMERIC(10, 2) NOT NULL,
    guest_fee NUMERIC(10, 2) NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    host_payout NUMERIC(10, 2) NULL,
    total_hours NUMERIC(10, 2) NOT NULL,
    property_rate NUMERIC(10, 2) NOT NULL,
    cancelation_policy VARCHAR(50) NULL,
    canceled_by VARCHAR(50) NULL,
    cancelation_reason VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL,
    cancellation_date TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (id),
    CONSTRAINT fk_property_bookings FOREIGN KEY (property_id)
        REFERENCES properties(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_guests_booking FOREIGN KEY (guest_id)
        REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_guest_id ON bookings(guest_id);
CREATE INDEX idx_property_id ON bookings(property_id);
CREATE INDEX idx_bookings_deleted ON bookings(deleted);
CREATE INDEX idx_bookings_deleted_at ON bookings(deleted_at);

CREATE TABLE reviews (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL, -- references User's id
    reviewee_id BIGINT NOT NULL, -- references User's id
    reviewer_role VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    comment TEXT NULL,
    is_public BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT uq_review_booking_reviewer UNIQUE (booking_id, reviewer_id),
    CONSTRAINT fk_review_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_review_reviewer FOREIGN KEY (reviewer_id)
        REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_review_reviewee FOREIGN KEY (reviewee_id)
        REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_review_deleted ON reviews(deleted);
CREATE INDEX idx_review_deleted_at ON reviews(deleted_at);

CREATE TABLE messages (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL, -- references User's id
    content TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_message PRIMARY KEY (id),
    CONSTRAINT fk_message_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_message_sender FOREIGN KEY (sender_id)
        REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_messages_deleted ON messages(deleted);
CREATE INDEX idx_messages_deleted_at ON messages(deleted_at);

CREATE TABLE payments (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    booking_id BIGINT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(50) NOT NULL,
    status VARCHAR(255) NOT NULL,
    method VARCHAR(255) NOT NULL,
    paid_at TIMESTAMPTZ NULL,
    refunded_at TIMESTAMPTZ NULL,
    refund_amount NUMERIC(10, 2) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id),
    CONSTRAINT uk_booking_id_payment UNIQUE (booking_id),
    CONSTRAINT fk_payment_booking FOREIGN KEY (booking_id)
        REFERENCES bookings(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX idx_payment_deleted ON payments(deleted);
CREATE INDEX idx_payment_deleted_at ON payments(deleted_at);

CREATE TABLE blocked_slots (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_id BIGINT NOT NULL,
    start_datetime TIMESTAMPTZ NOT NULL,
    end_datetime TIMESTAMPTZ NOT NULL,
    reason VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_blocked_slot PRIMARY KEY (id),
    CONSTRAINT fk_blocked_slot_property FOREIGN KEY (property_id)
        REFERENCES properties(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_blocked_slot_deleted ON blocked_slots(deleted);
CREATE INDEX idx_blocked_slot_deleted_at ON blocked_slots(deleted_at);

CREATE TABLE property_images (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    property_id BIGINT NOT NULL,
    url VARCHAR(512) NOT NULL, 
    is_main BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_property_image PRIMARY KEY (id),
    CONSTRAINT fk_property_image_property FOREIGN KEY (property_id)
        REFERENCES properties(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_property_image_deleted ON property_images(deleted);
CREATE INDEX idx_property_image_deleted_at ON property_images(deleted_at);

CREATE TABLE amenities (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    icon_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_amenity PRIMARY KEY (id),
    CONSTRAINT uk_amenity_name UNIQUE (name)
);

CREATE INDEX idx_amenity_deleted ON amenities(deleted);
CREATE INDEX idx_amenity_deleted_at ON amenities(deleted_at);

CREATE TABLE properties_amenities (
    property_id BIGINT NOT NULL,
    amenity_id BIGINT NOT NULL,
    CONSTRAINT pk_properties_amenities PRIMARY KEY (property_id, amenity_id),
    CONSTRAINT fk_properties_amenities_property FOREIGN KEY (property_id)
        REFERENCES properties(id) ON DELETE CASCADE,
    CONSTRAINT fk_properties_amenities_amenity FOREIGN KEY (amenity_id)
        REFERENCES amenities(id) ON DELETE CASCADE
);
